library(tidyverse)
library(ggpubr)
library(rstatix)
library(dplyr)
library(readxl)

finaldata_hho_4 <- read_excel("finaldata_hho_4.xlsx")
View(finaldata_hho_4)

kruskal.test(finaldata_hho_4$X1, finaldata_hho_4$cluster)
kruskal.test(finaldata_hho_4$X2, finaldata_hho_4$cluster)
kruskal.test(finaldata_hho_4$X3, finaldata_hho_4$cluster)
kruskal.test(finaldata_hho_4$X4, finaldata_hho_4$cluster)
kruskal.test(finaldata_hho_4$X5, finaldata_hho_4$cluster)
kruskal.test(finaldata_hho_4$X6, finaldata_hho_4$cluster)
kruskal.test(finaldata_hho_4$X7, finaldata_hho_4$cluster)
kruskal.test(finaldata_hho_4$X8, finaldata_hho_4$cluster)
kruskal.test(finaldata_hho_4$X9, finaldata_hho_4$cluster)
kruskal.test(finaldata_hho_4$X10, finaldata_hho_4$cluster)
kruskal.test(finaldata_hho_4$X11, finaldata_hho_4$cluster)
kruskal.test(finaldata_hho_4$X12, finaldata_hho_4$cluster)
kruskal.test(finaldata_hho_4$X13, finaldata_hho_4$cluster)
kruskal.test(finaldata_hho_4$X14, finaldata_hho_4$cluster)
kruskal.test(finaldata_hho_4$X15, finaldata_hho_4$cluster)
kruskal.test(finaldata_hho_4$X16, finaldata_hho_4$cluster)
kruskal.test(finaldata_hho_4$X17, finaldata_hho_4$cluster)
kruskal.test(finaldata_hho_4$X18, finaldata_hho_4$cluster)
kruskal.test(finaldata_hho_4$X19, finaldata_hho_4$cluster)
kruskal.test(finaldata_hho_4$X20, finaldata_hho_4$cluster)
kruskal.test(finaldata_hho_4$X21, finaldata_hho_4$cluster)
kruskal.test(finaldata_hho_4$X22, finaldata_hho_4$cluster)
kruskal.test(finaldata_hho_4$X23, finaldata_hho_4$cluster)
kruskal.test(finaldata_hho_4$X24, finaldata_hho_4$cluster)
kruskal.test(finaldata_hho_4$X25, finaldata_hho_4$cluster)
kruskal.test(finaldata_hho_4$X26, finaldata_hho_4$cluster)
kruskal.test(finaldata_hho_4$X27, finaldata_hho_4$cluster)
kruskal.test(finaldata_hho_4$X28, finaldata_hho_4$cluster)
kruskal.test(finaldata_hho_4$X29, finaldata_hho_4$cluster)
kruskal.test(finaldata_hho_4$X30, finaldata_hho_4$cluster)


